# Generated by Django 5.2.11 on 2026-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='city',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='annonce',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='annonce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('service_offer', 'Service proposé'), ('service_request', 'Service recherché'), ('item_sale', 'Objet à vendre'), ('item_request', 'Objet recherché'), ('urgent_help', 'Aide urgente')], max_length=30),
        ),
    ]
