# Generated by Django 5.2.11 on 2026-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_rename_city_annonce_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('deleted', 'Supprimée')], default='active', max_length=20),
        ),
    ]
