# Generated by Django 5.2.11 on 2026-02-15 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_annonce_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='reservation_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='reservation_status',
            field=models.CharField(choices=[('none', 'Aucune'), ('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='none', max_length=20),
        ),
    ]
