# Generated by Django 5.2.11 on 2026-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_annonce_reservation_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='quartier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
