# Generated by Django 5.2.11 on 2026-02-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_annonce_quartier_annonce_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='scam_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='annonce',
            name='scam_score',
            field=models.IntegerField(default=0),
        ),
    ]
