# Generated by Django 5.2.11 on 2026-02-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_annonce_status'),
        ('users', '0002_user_is_verified_user_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='annonces.annonce'),
        ),
    ]
